Fix compilation with C++17 standard, std::unary_function unavailable
Compilation fails using Clang 16 with "-std=c++17" in effect.
std::unary_function has been removed in this standard and is
replaced by std::function.

messagelib/messagecomposer/src/composer/keyresolver.cpp:348: error: no template
   named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
/usr/include/c++/v1/__functional/unary_function.h:46: note: '__unary_function' declared here