webengineviewer: Add missing Qt::PrintSupport link
This commit fixes the following error while cross-compiling for Android.

```
webengineviewer/src/webenginepage.cpp:19:10: fatal error: 'QPrinter' file not found
   19 | #include <QPrinter>
      |          ^~~~~~~~~~
```